let weight = [
    ['Bowser', '135'],
    ['King K. Rool', '133'],
    ['Donkey Kong', '127'],
    ['King Dedede', '127'],
    ['Ganondorf', '118'],
    ['Charizard', '116'],
    ['Incineroar', '116'],
    ['Kazuya', '113'],
    ['Piranha Plant', '112'],
    ['Samus', '108'],
    ['Dark Samus', '108'],
    ['Bowser Jr.', '108'],
    ['Terry', '108'],
    ['Wario', '107'],
    ['Ike', '107'],
    ['Ridley', '107'],
    ['Simon', '107'],
    ['Richter', '107'],
    ['Snake', '106'],
    ['Banjo & Kazooie', '106'],
    ['R.O.B.', '106'],
    ['Link', '104'],
    ['Yoshi', '104'],
    ['Captain Falcon', '104'],
    ['Mii Gunner', '104'],
    ['MinMin', '104'],
    ['Ryu', '103'],
    ['Ken', '103'],
    ['Mega Man', '102'],
    ['Hero', '101'],
    ['Mii Swordfighter', '100'],
    ['Cloud', '100'],
    ['Mario', '98'],
    ['Dr. Mario', '98'],
    ['Corrin', '98'],
    ['Pyra', '98'],
    ['Byleth', '97'],
    ['Luigi', '97'],
    ['Shulk', '97'],
    ['Pit', '96'],
    ['Dark Pit', '96'],
    ['Ivysaur', '96'],
    ['Wii Fit Trainer', '96'],
    ['Roy', '95'],
    ['Chrom', '95'],
    ['Robin', '95'],
    ['Pac-Man', '95'],
    ['Ness', '94'],
    ['Lucas', '94'],
    ['Mii Brawler', '94'],
    ['Inkling', '94'],
    ['Joker', '93'],
    ['Ice Climbers', '92'],
    ['Lucario', '92'],
    ['Wolf', '92'],
    ['Villager', '92'],
    ['Steve', '92'],
    ['Mythra', '92'],
    ['Toon Link', '91'],
    ['Palutena', '91'],
    ['Marth', '90'],
    ['Diddy Kong', '90'],
    ['Lucina', '90'],
    ['Peach', '89'],
    ['Daisy', '89'],
    ['Young Link', '88'],
    ['Greninja', '88'],
    ['Isabelle', '88'],
    ['Little Mac', '87'],
    ['Sonic', '86'],
    ['Duck Hunt', '86'],
    ['Zelda', '85'],
    ['Sora', '85'],
    ['Falco', '82'],
    ['Rosalina', '82'],
    ['Bayonetta', '81'],
    ['Meta Knight', '80'],
    ['Zero Suit Samus', '80'],
    ['Sephiroth', '79'],
    ['Kirby', '79'],
    ['Pikachu', '79'],
    ['Olimar', '79'],
    ['Mewtwo', '79'],
    ['Sheik', '78'],
    ['Fox', '77'],
    ['Mr. Game & Watch', '75'],
    ['Squirtle', '75'],
    ['Jigglypuff', '68'],
    ['Pichu', '62']
]

export default weight;